name: Build & Push
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push image
    - name: Build and Push
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gitopsy-demo:${{ github.sha }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/gitopsy-demo:${{ github.sha }}
    - name: Checkout GitOps repo
      uses: actions/checkout@v3
      with:
        repository: 0marMejdi/config-gitopsy
        # token: ${{ secrets.GITHUB_TOKEN }}
        path: config-gitopsy
        ref: main

    - name: Update Helm values
      run: |
        IMAGE_TAG=${GITHUB_SHA::7}
        sed -i "s/^  tag: .*/  tag: $IMAGE_TAG/" config-gitopsy/app/values.yaml

    - name: Commit and push changes
      run: |
        cd config-gitopsy
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update image tag to $IMAGE_TAG"
        git push
